version: 2.3.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  project: seq-client.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: owIruqEXZlFwqcSBYyjR19/8EodS+aXFzZmBwqlaYnDE/uy1X+KsuI5QH3p9iBmx
  on:
    branch: master
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
